"""add sequence column to CampaignHistory

Revision ID: 49277ce5a872
Revises: 33e15691f9ed
Create Date: 2026-08-13 20:54:31.130820

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '49277ce5a872'
down_revision = '33e15691f9ed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('campaign_history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sequence', sa.Integer(), nullable=True))

    # Backfill missing values with a default before setting non-nullable
    # For records without sequence_after, we'll default to 0 or another marker to indicate data issue
    op.execute("UPDATE campaign_history SET sequence = COALESCE(sequence_after, 0) WHERE sequence IS NULL")

    with op.batch_alter_table('campaign_history', schema=None) as batch_op:
        batch_op.alter_column('sequence', nullable=False)
        batch_op.create_index(batch_op.f('ix_campaign_history_sequence'), ['sequence'], unique=False)
        batch_op.create_unique_constraint('uix_campaign_sequence', ['campaign_id', 'sequence'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('campaign_history', schema=None) as batch_op:
        batch_op.drop_constraint('uix_campaign_sequence', type_='unique')
        batch_op.drop_index(batch_op.f('ix_campaign_history_sequence'))
        batch_op.drop_column('sequence')

    # ### end Alembic commands ###

