"""add edited_at to campaign_history

Revision ID: 4bbfb747eca2
Revises: efc183012539
Create Date: 2026-08-15 07:11:00.539909

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4bbfb747eca2'
down_revision = 'efc183012539'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('campaign_history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('edited_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('campaign_history', schema=None) as batch_op:
        batch_op.drop_column('edited_at')

    # ### end Alembic commands ###
