"""Add nullable domain status

Revision ID: 7ddc3d0ffeba
Revises: 4bbfb747eca2
Create Date: 2026-08-17 19:11:08.733561

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7ddc3d0ffeba'
down_revision = '4bbfb747eca2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('domains', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('domains', schema=None) as batch_op:
        batch_op.drop_column('status')

    # ### end Alembic commands ###
