"""add settings table

Revision ID: efc183012539
Revises: 7f3a1c9c4d2e
Create Date: 2026-08-14 22:18:27.649894

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'efc183012539'
down_revision = '7f3a1c9c4d2e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('settings',
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('value', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('key')
    )
    with op.batch_alter_table('campaign_history', schema=None) as batch_op:
        batch_op.alter_column('sequence',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('campaign_history', schema=None) as batch_op:
        batch_op.alter_column('sequence',
               existing_type=sa.INTEGER(),
               nullable=False)

    op.drop_table('settings')
    # ### end Alembic commands ###
