"""add history_email_used table

Revision ID: f79a5e5aaa45
Revises: migrate_actiontype_enum
Create Date: 2026-08-22 02:35:37.901224

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f79a5e5aaa45'
down_revision = 'migrate_actiontype_enum'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('history_email_used',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('history_id', sa.Integer(), nullable=False),
    sa.Column('email_code', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['email_code'], ['email_accounts.code'], ),
    sa.ForeignKeyConstraint(['history_id'], ['campaign_history.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('history_id', 'email_code', name='uix_history_email')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('history_email_used')
    # ### end Alembic commands ###
